site_name: Nova Documentation
site_url: https://nova-dl.org
site_description: Natural Language Interface for Deep Learning
site_author: Nova Team

repo_name: nova-team/nova
repo_url: https://github.com/nova-team/nova

theme:
  name: material
  palette:
    primary: indigo
    accent: purple
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/brain
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.tabs.link

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Language Guide:
    - Overview: language-guide/overview.md
    - Core Concepts: language-guide/core-concepts.md
    - Syntax: language-guide/syntax.md
    - Translation Process: language-guide/translation-process.md
  - Examples:
    - Basic Models: examples/basic-models.md
    - Computer Vision: examples/computer-vision.md
  - API Reference:
    - Interpreter: api/interpreter.md
    - Extensions: api/extensions.md
  - Community:
    - Contributing: community/contributing.md
    - Roadmap: community/roadmap.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nova-team/nova
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/nova-dl/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/font-size.js

plugins:
  - search